config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  devise_for :users, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  
  match "/split" => Split::Dashboard, anchor: false, via: [:get, :post, :delete], constraints: ->(request) do
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    
    request.env['warden'].user.is_admin?
  end

  get 'home/welcome'
  get 'health_check', to: 'home#health_check'
  get 'login', to: 'home#login'
  get 'sso/:id', to: 'home#sso', as: 'sso'
  get 'token/:id', to: 'token#show', as: 'token'

  get 'candidates/:fellow_opportunity_id/status', to: 'candidates#status', as: 'candidate_status'
  
  resources :fellows, only: [:edit, :update]

  namespace :fellow do
    get 'home/welcome'
    post 'home/career'
    
    resource :profile, only: [:show, :edit, :update] do
      get :unsubscribe
    end
    
    resources :opportunities, only: [:show, :update]
  end

  namespace :admin do
    get 'home/welcome'
    get 'home/new_opportunity', as: 'new_opportunity'

    resources :employers, shallow: true do
      resources :locations
      resources :opportunities do
        resources :candidates, only: [:index, :create, :update, :destroy]
      end
    end
  
    resources :opportunities, only: [:index] do
      collection do
        post :export
      end
      
      member do
        put :unpublish
      end
    end

    resources :sites, shallow: true do
      resources :courses, except: [:index]
    end

    resources :fellows do
      collection do
        get :upload
        post :upload
      end
      
      member do
        get :resume
      end
    end

    resources :fellow_opportunities
    resources :opportunity_stages
    resources :employment_statuses
    resources :coaches

    resources :interests do
      collection do
        get :list
      end
    end

    resources :industries do
      collection do
        get :list
        get :combined
      end
    end

    resources :metros, only: [:index] do
      collection do
        get :list
        get :search
      end
    end
    
    resources :majors, only: [:index] do
      collection do
        get :list
      end
    end
    
    resources :cohort_fellows
    resources :cohorts
  end
  
  root to: "home#welcome"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employer.rb
require 'taggable'

class Employer < ApplicationRecord
  include Taggable

  has_many :opportunities, dependent: :destroy
  has_many :locations, as: :locateable, dependent: :destroy
  
  has_and_belongs_to_many :coaches, dependent: :destroy
  
  taggable :industries
  
  accepts_nested_attributes_for :industries

  validates :name, presence: true, uniqueness: true

  def industry_tags
    industries.pluck(:name).join(';')
  end
  
  def industry_tags= tag_string
    self.industry_ids = Industry.where(name: tag_string.split(';')).pluck(:id)
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :locateable, polymorphic: true

  has_one :contact, as: :contactable, dependent: :destroy
  accepts_nested_attributes_for :contact
  
  has_and_belongs_to_many :opportunities, dependent: :destroy
  
  validates :name, uniqueness: {scope: [:locateable_id, :locateable_type]}, unless: Proc.new{|location| location.name.blank?}
  
  def label
    "#{name}: #{contact.address_1} #{contact.city}, #{contact.state}"
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin!
  before_action :set_employer
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = @locations.build
    @location.build_contact
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = @locations.build(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to admin_location_path(@location), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to admin_location_path(@location), notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    employer = @location.locateable
    @location.destroy

    respond_to do |format|
      format.html { redirect_to admin_employer_locations_url(employer), notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def set_employer
    @employer = Employer.find(params[:employer_id]) if params[:employer_id]
    @locations = @employer ? @employer.locations : Location.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = @locations.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(
      :name, 
      contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
    )
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_check_boxes.html.erb
<% object_name = object.class.name.downcase %>  

<div class="locations checklist">
  <h3>Locations</h3>
  <% parent.locations.order('name asc').each do |location| %>
    <% tag_id = "location_ids_#{location.id}" %>
    
    <%= check_box_tag("#{object_name}[location_ids][]", location.id, object.locations.include?(location), id: tag_id, 'data-zip' => location.contact.postal_code, class: 'location') %>
    <%= label_tag(tag_id, location.label, style: 'display: inline;') %><br>
  <% end %>
</div>

app/views/admin/locations/_form.html.erb
<%= form_with(model: [:admin, employer, location], local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>
  
  <%= render 'admin/contacts/nested_form', form: form %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/locations/_list.html.erb
<% if locations.empty? %>
  <p class="empty-list">There are no locations for this employer yet.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th><%= locations.first.locateable.class.name %></th>
        <th>Name</th>
        <th>Address</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% locations.order('name asc').each do |location| %>
        <tr>
          <td><%= location.locateable.name %>
          <td><%= link_to location.name, admin_location_path(location) %></td>
          <td><%= location.label %></td>
          <td><%= link_to 'Edit', edit_admin_location_path(location), class: 'edit' %></td>
          <td><%= link_to 'Delete', admin_location_path(location), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', employer: @employer, location: @location %>

<%= link_to 'Show', admin_location_path(@location) %> |
<%= link_to 'Back', :back %>

app/views/admin/locations/index.html.erb
<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to 'Show', admin_employer_location_path(@employer) %></td>
        <td><%= link_to 'Edit', edit_admin_employer_location_path(@employer, location) %></td>
        <td><%= link_to 'Destroy', admin_employer_location_path(@employer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_admin_employer_location_path %>

app/views/admin/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', employer: @employer, location: @location %>

<%= link_to 'Back', :back %>

app/views/admin/locations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<footer class="actions">
  <%= link_to 'Edit', edit_admin_location_path(@location), class: 'edit' %> |
  <%= link_to 'Back', :back, class: 'back' %>
</footer>