config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  devise_for :users, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  
  match "/split" => Split::Dashboard, anchor: false, via: [:get, :post, :delete], constraints: ->(request) do
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    
    request.env['warden'].user.is_admin?
  end

  get 'home/welcome'
  get 'health_check', to: 'home#health_check'
  get 'login', to: 'home#login'
  get 'sso/:id', to: 'home#sso', as: 'sso'
  get 'token/:id', to: 'token#show', as: 'token'

  get 'candidates/:fellow_opportunity_id/status', to: 'candidates#status', as: 'candidate_status'
  
  resources :fellows, only: [:edit, :update]

  namespace :fellow do
    get 'home/welcome'
    post 'home/career'
    
    resource :profile, only: [:show, :edit, :update] do
      get :unsubscribe
    end
    
    resources :opportunities, only: [:show, :update]
  end

  namespace :admin do
    get 'home/welcome'
    get 'home/new_opportunity', as: 'new_opportunity'

    resources :employers, shallow: true do
      resources :locations
      resources :opportunities do
        resources :candidates, only: [:index, :create, :update, :destroy]
      end
    end
  
    resources :opportunities, only: [:index] do
      collection do
        post :export
      end
      
      member do
        put :unpublish
      end
    end

    resources :sites, shallow: true do
      resources :courses, except: [:index]
    end

    resources :fellows do
      collection do
        get :upload
        post :upload
      end
      
      member do
        get :resume
      end
    end

    resources :fellow_opportunities
    resources :opportunity_stages
    resources :employment_statuses
    resources :coaches

    resources :interests do
      collection do
        get :list
      end
    end

    resources :industries do
      collection do
        get :list
        get :combined
      end
    end

    resources :metros, only: [:index] do
      collection do
        get :list
        get :search
      end
    end
    
    resources :majors, only: [:index] do
      collection do
        get :list
      end
    end
    
    resources :cohort_fellows
    resources :cohorts
  end
  
  root to: "home#welcome"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/opportunity.rb
require 'taggable'

class Opportunity < ApplicationRecord
  include Taggable
  
  belongs_to :employer
  belongs_to :opportunity_type
  belongs_to :region
  
  has_many :tasks, as: :taskable, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
  
  has_many :fellow_opportunities
  has_many :fellows, through: :fellow_opportunities
  
  taggable :industries, :interests, :majors, :industry_interests, :metros

  has_and_belongs_to_many :locations, dependent: :destroy, after_add: :attach_metro
  accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true
  
  serialize :steps, Array
  
  validates :name, presence: true
  validates :job_posting_url, url: {ensure_protocol: true}
  validate :validate_locateable
  
  scope :prioritized, -> { order(priority: :asc) }
  
  before_save :set_priority
  
  class << self
    def csv_headers
      ['Region', 'Employer', 'Position', 'Type', 'Location', 'Link', 'Employer Partner', 'Inbound', 'Recurring', 'Interests']
    end
  end
  
  def candidates search_params=nil
    search_params ||= {}
    return @candidates if defined?(@candidates)
    
    candidate_ids = Fellow.receive_opportunities.pluck(:id)

    candidate_ids &= fellow_ids_for_opportunity_type
    
    if search_params[:employment_statuses] && !search_params[:employment_statuses].empty?
      candidate_ids &= fellow_ids_for_employment_statuses(search_params[:employment_statuses])
    end
    
    
    unless [:industries_interests, :majors].all?{|key| search_params[key] == ''}
      career_interests = [:industries_interests, :majors].map{|i| (search_params[i] || '').split(';')}.flatten.compact.uniq.sort.join(';')
      career_interests = nil if career_interests.blank?
      
      candidate_ids &= fellow_ids_for_industries_interests(career_interests)
    end

    unless search_params[:metros] == ''
      candidate_ids &= fellow_ids_for_metros(search_params[:metros])
    end

    candidate_ids.uniq!
    
    # remove already-activated candidates
    candidate_ids -= fellow_opportunities.pluck(:fellow_id)
    
    @candidates = Fellow.where(id: candidate_ids)
  end
  
  def formatted_name
    [employer.name, name].join(' - ')
  end
  
  def fellow_ids_for_employment_statuses employment_status_ids
    Fellow.where(employment_status_id: employment_status_ids).pluck(:id)
  end
  
  def fellow_ids_for_opportunity_type
    self.class.connection.query("select fellow_id from fellows_opportunity_types where opportunity_type_id = #{opportunity_type.id}").flatten.uniq
  end
  
  def fellow_ids_for_interests names
    selected_ids = if names
      Interest.where(name: names.split(';')).pluck(:id)
    else
      interest_ids
    end
    
    FellowInterest.fellow_ids_for(selected_ids)
  end
  
  def fellow_ids_for_industries names
    selected_ids = if names
      Industry.where(name: names.split(';')).pluck(:id)
    else
      industry_ids
    end
    
    FellowIndustry.fellow_ids_for(selected_ids)
  end
  
  def fellow_ids_for_majors names
    named = if names
      Major.where(name: names.split(';'))
    else
      majors
    end
    
    parent_ids = named.map(&:all_parents).flatten.uniq.map(&:id)
    child_ids = named.map(&:all_children).flatten.uniq.map(&:id)
    
    selected_ids = (named.pluck(:id) + parent_ids + child_ids).uniq
    
    FellowMajor.fellow_ids_for(selected_ids)
  end
  
  def fellow_ids_for_industries_interests names
    industry_fellow_ids = fellow_ids_for_industries names
    interest_fellow_ids = fellow_ids_for_interests names
    major_fellow_ids = fellow_ids_for_majors names
    
    industry_fellow_ids | interest_fellow_ids | major_fellow_ids
  end
  
  def fellow_ids_for_metros names
    named = if names
      Metro.where(name: names.split(';'))
    else
      metros
    end
    
    parent_ids = named.map(&:all_parents).flatten.uniq.map(&:id)
    child_ids = named.map(&:all_children).flatten.uniq.map(&:id)
    
    selected_ids = (named.pluck(:id) + parent_ids + child_ids).uniq
    
    FellowMetro.fellow_ids_for(selected_ids)
  end
  
  def state_ids_for_metro_ids metro_ids
    state_abbrs = Metro.city.where(id: metro_ids).map(&:states).flatten.uniq
    Metro.where(code: state_abbrs).pluck(:id)
  end
  
  def metro_ids_for_state_ids metro_ids
    state_abbrs = Metro.state.where(id: metro_ids).pluck(:code)
    Metro.city.reject{|c| (c.states & state_abbrs).empty?}.map(&:id)
  end
  
  def candidate_ids= candidate_id_list
    initial_stage = OpportunityStage.find_by position: 0
    
    fellow_opps = candidate_id_list.map do |candidate_id|
      if archived = archived_fellow_opp(candidate_id)
        archived.restore
      else
        fellow_opportunities.create! fellow_id: candidate_id, opportunity_stage: initial_stage
      end
    end
    
    notify_candidates(fellow_opps)
  end
  
  def notify_candidates fellow_opportunities_list
    fellow_opportunities_list.each do |fellow_opp|
      access_token = AccessToken.for(fellow_opp)
      CandidateMailer.with(access_token: access_token).respond_to_invitation.deliver_later
    end
  end
  
  def postal_codes
    locations.map(&:contact).compact.map(&:postal_code).compact
  end
  
  def csv_fields
    begin
      [
        region.name,
        employer.name,
        name,
        opportunity_type.name,
        primary_city_state,
        job_posting_url,
        (employer.employer_partner ? 'yes' : 'no'),
        (inbound ? 'yes' : 'no'),
        (recurring ? 'yes' : 'no'),
        (interests + industries + majors).map(&:name).uniq.sort.join(', ')
      ]
    # rescue => e
    #   Rails.logger.info("COULD NOT EXPORT OPP #{id}: #{e.message}")
    #   nil
    end
  end
  
  def primary_city_state
    if metros.first
      metro_name = metros.first.name
      
      city, state = metro_name.split(/,\s+/)
    
      return metro_name unless state
      primary_state, secondary_state = state.split('-', 2)
    
      [city, primary_state].join(', ')
    else
      contact = locations.first.contact
      
      [contact.city, contact.state].join(', ')
    end
  end
  
  # lowest priority is best/first
  def calculated_priority
    employer_partner = employer.employer_partner
    
    value = if employer_partner && inbound && recurring
      0
    elsif employer_partner && inbound
      1
    elsif inbound
      2
    elsif employer_partner && recurring
      3
    elsif employer_partner
      4
    elsif recurring
      5
    else
      6
    end
    
    value += 10 if published?
    
    value
  end
  
  def unpublish!
    update published: false
  end
  
  def set_default_industries
    self.industry_ids = employer.industry_ids
  end
  
  private
  
  def archived_fellow_opp candidate_id
    FellowOpportunity.with_deleted.find_by(opportunity_id: self.id, fellow_id: candidate_id)
  end
  
  def attach_metro location
    return if location.contact.nil?
    
    metro = location.contact.metro
    return if metro.nil?
    
    metros << metro unless metros.include?(metro)
  end
  
  def validate_locateable
    errors.add(:location, "must contain a zip code or a metro area") unless is_locateable?
  end
  
  def is_locateable?
    has_metro? || has_postal_code?
  end
  
  def has_metro?
    !metros.empty?
  end
  
  def has_postal_code?
    !postal_codes.empty?
  end
  
  def set_priority
    self.priority = calculated_priority
  end
end

app/models/opportunity_type.rb
class OpportunityType < ApplicationRecord
  has_many :opportunities
  
  has_and_belongs_to_many :fellows
  
  validates :name, :position, presence: true, uniqueness: true
  
  class << self
    def types
      return @types if defined?(@types)
      @types = YAML.load(File.read("#{Rails.root}/config/opportunity_types.yml"))
    end
  end
end

app/controllers/admin/opportunities_controller.rb
class Admin::OpportunitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin!
  before_action :set_employer
  before_action :set_opportunity, only: [:show, :edit, :update, :unpublish, :destroy]

  # GET /opportunities
  # GET /opportunities.json
  def index
  end
  
  def export
    respond_to do |format|
      format.csv do
        @opportunities = unpaginated_opportunities
        Rails.logger.info("OPPS: #{@opportunities.inspect}")
        Opportunity.where(id: @opportunities.map(&:id)).update_all(published: true)
    
        headers['Content-Disposition'] = "attachment; filename=\"opportunities.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /opportunities/1
  # GET /opportunities/1.json
  def show
  end

  # GET /opportunities/new
  def new
    @opportunity = @opportunities.build
    @opportunity.tasks.build
    @opportunity.set_default_industries
  end

  # GET /opportunities/1/edit
  def edit
    @opportunity.tasks.build
  end

  # POST /opportunities
  # POST /opportunities.json
  def create
    @opportunity = @opportunities.build(opportunity_params)

    respond_to do |format|
      if @opportunity.save
        format.html { redirect_to admin_employer_opportunities_path(@opportunity.employer), notice: 'Opportunity was successfully created.' }
        format.json { render :show, status: :created, location: @opportunity }
      else
        format.html { render :new }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opportunities/1
  # PATCH/PUT /opportunities/1.json
  def update
    respond_to do |format|
      if @opportunity.update(opportunity_params)
        format.html { redirect_to admin_employer_opportunities_path(@opportunity.employer), notice: 'Opportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @opportunity }
      else
        format.html { render :edit }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def unpublish
    @opportunity.unpublish!
    redirect_to request.referer
  end

  # DELETE /opportunities/1
  # DELETE /opportunities/1.json
  def destroy
    employer = @opportunity.employer
    @opportunity.destroy

    respond_to do |format|
      format.html { redirect_to admin_employer_opportunities_url(employer), notice: 'Opportunity was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  
  def set_employer
    @employer = Employer.find(params[:employer_id]) if params[:employer_id]
    @opportunities = (@employer ? @employer.opportunities : Opportunity).prioritized.paginate(page: params[:page])
    
    unless params[:region_id].blank?
      @opportunities = @opportunities.where(region_id: params[:region_id])
    end
  end
  
  def unpaginated_opportunities
    (@employer ? @employer.opportunities : Opportunity).where(id: params[:export_ids]).prioritized.sort_by{|o| o.region.position}
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_opportunity
    @opportunity = @opportunities.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def opportunity_params
    params.require(:opportunity).permit(
      :_destroy,
      :name, :summary, :employer_id, :job_posting_url, :application_deadline, 
      :inbound, :recurring, :opportunity_type_id, :region_id, :how_to_apply, :referral_email,
      :industry_tags, :interest_tags, :metro_tags, :major_tags, :industry_interest_tags,
      steps: [],
      industry_ids: [], interest_ids: [], metro_ids: [], major_ids: [], location_ids: [],
      locations_attributes: [
        :_destroy, :id, :name, :locateable_id, :locateable_type,
        contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
      ]
    )
  end
end

app/controllers/fellow/opportunities_controller.rb
class Fellow::OpportunitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_fellow!
  before_action :set_fellow
  before_action :set_candidate

  def show
    @content = YAML.load(File.read("#{Rails.root}/config/opportunity_stage_content.yml"))

    @fellow_opp = @candidate
    @fellow = @fellow_opp.fellow
    @opportunity = @fellow_opp.opportunity
    
    @token = AccessToken.for(@fellow_opp)
    @opportunity_stage = @fellow_opp.opportunity_stage
  end

  def update
    # if @fellow.update(fellow_params)
    #   redirect_to fellow_profile_path, notice: 'Your profile was successfully updated.'
    # else
    #   render :edit
    # end
  end
  
  private
  
  def set_fellow
    if @access_token
      @fellow = @access_token.owner.fellow
      return
    end
    
    unless current_user.fellow
      current_user.create_fellow(
        first_name: 'unknown',
        last_name: 'unknown',
        employment_status: EmploymentStatus.find_by(position: 0)
      )
    end
    
    @fellow = current_user.fellow
  end
  
  def set_candidate
    @candidate = @fellow.fellow_opportunities.find_by(id: params[:id])
  end
  
  def fellow_params
    # params.require(:fellow).permit(
    #   :key, :first_name, :last_name, :graduation_year, :graduation_semester,
    #   :major, :affiliations, :linkedin_url,
    #   :employment_status_id, :industry_tags, :interest_tags, :metro_tags, :industry_interest_tags,
    #   industry_ids: [], interest_ids: [], metro_ids: [],
    #   contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
    # )
  end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
  def new_task_fields index
    <<-TASK_FIELDS
      <li class="removeable_fields">
        <div class="field">
          <label for="opportunity_tasks_attributes_#{index}_name">Name</label>
          <input type="text" name="opportunity[tasks_attributes][#{index}][name]" id="opportunity_tasks_attributes_#{index}_name" />
        </div>
    
        <div class="field">
          <label for="opportunity_tasks_attributes_#{index}_due_at">Due at</label>
          <input class="datetime" type="text" name="opportunity[tasks_attributes][#{index}][due_at]" id="opportunity_tasks_attributes_#{index}_due_at" /><br>

          <input class="remove_hidden" type="hidden" value="false" name="opportunity[tasks_attributes][#{index}][_destroy]" id="opportunity_tasks_attributes_#{index}__destroy" />
          <a class="remove" href="#">remove</a>
        </div>
      </li>
    TASK_FIELDS
  end
end

app/views/admin/opportunities/_form.html.erb
<%= form_with(model: [:admin, employer, opportunity], local: true) do |form| %>
  <% if opportunity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opportunity.errors.count, "error") %> prohibited this opportunity from being saved:</h2>

      <ul>
      <% opportunity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Opportunity Name or Job Title' %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.label :referral_email, 'Referral Contact E-mail' %>
    <%= form.text_field :referral_email %>
  </div>

  <div class="field">
    <%= form.label :opportunity_type_id, 'Opportunity Type' %>
    <%= form.collection_select(:opportunity_type_id, OpportunityType.order(position: :asc), :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :region_id, 'Region' %>
    <%= form.collection_select(:region_id, Region.order(position: :asc), :id, :name) %>
  </div>

  <div class="field">
    <%= form.check_box :inbound %>
    <%= form.label :inbound, 'Inbound?', class: 'checkbox' %>
  </div>

  <div class="field">
    <%= form.check_box :recurring %>
    <%= form.label :recurring, 'Recurring?', class: 'checkbox' %>
  </div>

  <div class="field">
    <%= form.label :summary, 'Summary (make it specific, explain acronyms, and keep it short!)' %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :how_to_apply, 'How to Apply' %>
    <%= form.text_area :how_to_apply %>
  </div>

  <div class="field">
    <%= form.label :job_posting_url, 'Direct link to the job posting (i.e. not just the homepage)' %>
    <%= form.text_field :job_posting_url, required: true %>
  </div>
  
  <div class="field">
    <%= form.label :application_deadline %>
    <%= form.text_field :application_deadline, class: 'datetime' %>
  </div>
  
  <%= render 'admin/locations/check_boxes', parent: opportunity.employer, object: opportunity %>
  
  <ul class="location_forms" data-employer-id="<%= opportunity.employer.id %>">
    <%= form.fields_for :locations do |location_form| %>
      <% next unless location_form.object.new_record? %>
      
      <li class="location_fields removeable_fields">
        <%= location_form.hidden_field :locateable_id, value: opportunity.employer.id %>
        <%= location_form.hidden_field :locateable_type, value: 'Employer' %>
        
        <div class="field">
          <%= location_form.label :name %>
          <%= location_form.text_field :name, required: true %>
          <%= location_form.hidden_field :_destroy, class: 'remove_hidden' %>
          <%= link_to 'remove', '#', class: 'remove' %>
        </div>

        <%= location_form.fields_for :contact do |contact_form| %>
          <div class="field">
            <%= contact_form.label :address_1 %>
            <%= contact_form.text_field :address_1 %>
          </div>

          <div class="field">
            <%= contact_form.label :address_2 %>
            <%= contact_form.text_field :address_2 %>
          </div>

          <div class="field">
            <%= contact_form.label :city %>
            <%= contact_form.text_field :city %>
          </div>

          <div class="field">
            <%= contact_form.label :state %>
            <%= contact_form.select :state, Contact::STATES %>
          </div>

          <div class="field">
            <%= contact_form.label :postal_code %>
            <%= contact_form.text_field :postal_code, class: 'postal_code' %>
          </div>

          <div class="field">
            <%= contact_form.label :phone %>
            <%= contact_form.text_field :phone %>
          </div>

          <div class="field">
            <%= contact_form.label :email %>
            <%= contact_form.text_field :email %>
          </div>

          <div class="field">
            <%= contact_form.label :url %>
            <%= contact_form.text_field :url %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>

  <p><%= link_to '+add a location', '#', class: 'new_location' %></p>
  
  <h3>Required Steps</h3>
  
  <p>
    <% OpportunityStage.togglable_names.each do |stage_name| %>
      <% tag_id = "steps_#{stage_name.underscore}" %>

      <%= check_box_tag("opportunity[steps][]", stage_name, true, id: tag_id) %>
      <%= label_tag(tag_id, stage_name, style: 'display: inline;') %><br>
    <% end %>
  </p>
  
  <div id="interests-collection">
    <h3>Industries/Interests</h3>

    <%= link_to 'full list', combined_admin_industries_path, target: '_blank' %>
  
    <div id="industry-interest-tags" class="jquery-tags">
      <%= form.text_area :industry_interest_tags %>
    </div>
  </div>
  
  <div id="majors">
    <h3>Majors/Minors (Related Courses of Study)</h3>

    <%= link_to 'full list', list_admin_majors_path, target: '_blank' %>
  
    <div id="major-tags" class="jquery-tags">
      <%= form.text_area :major_tags, class: 'major-tags' %>
    </div>
  </div>
  
  <div id="metros-collection">
    <h3>Metro Areas</h3>

    <%= link_to 'full list', list_admin_metros_path, target: '_blank' %>
  
    <div id="metro-tags" class="jquery-tags">
      <%= form.text_area :metro_tags, class: 'metro-tags' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/opportunities/_list.html.erb
<%= form_tag admin_opportunities_path, method: :get, id: 'opportunity-filters' do %>
  <%= select_tag(:region_id, options_from_collection_for_select(Region.order(position: :asc), :id, :name, params[:region_id]), include_blank: 'filter by region')%>
  
  <%= submit_tag 'filter' %>
<% end %>

<% if opportunities.empty? %>
  <p class="empty-list">There are no opportunties to show here.</p>
<% else %>
  <%= form_tag export_admin_opportunities_path(format: 'csv'), method: :post do %>
    <table class="wide">
      <thead>
        <tr>
          <th>Employer</th>
          <th>Title</th>
          <th>Summary</th>
          <th>Deadline</th>
          <th>Published</th>
          <th>Partner</th>
          <th>Inbound</th>
          <th>Recurring</th>
          <th>Actions</th>
          <th class="numeric">Export</th>
        </tr>
      </thead>

      <tbody>
        <% opportunities.each do |opportunity| %>
          <tr>
            <td><%= opportunity.employer.name %>
            <td><%= link_to opportunity.name, admin_opportunity_path(opportunity) %></td>
            <td><%= truncate(opportunity.summary, length: 100, separator: ' ') %></td>
            <td><%= date_format(opportunity.application_deadline) %></td>
            <td class="checkmark"><%= checkmark(opportunity.published?) %></td>
            <td class="checkmark"><%= checkmark(opportunity.employer.employer_partner) %>
            <td class="checkmark"><%= checkmark(opportunity.inbound) %></td>
            <td class="checkmark"><%= checkmark(opportunity.recurring) %></td>
            <td>
              <%= link_to 'Edit', edit_admin_opportunity_path(opportunity), class: 'edit' %><br/>
              <%= link_to 'Delete', admin_opportunity_path(opportunity), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %><br />
              <%= link_to('Unpublish', unpublish_admin_opportunity_path(opportunity), method: :put, class: 'edit') if opportunity.published? %>
            </td>
            <td class="numeric"><%= check_box_tag 'export_ids[]', opportunity.id, !opportunity.published %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p><%= submit_tag 'Export to CSV' %></p>
  <% end %>
<% end %>

app/views/admin/opportunities/edit.html.erb
<h1>Editing Opportunity</h1>

<%= render 'form', employer: @employer, opportunity: @opportunity %>

<%= link_to 'Show', admin_opportunity_path(@opportunity) %> |
<%= link_to 'Back', admin_employer_opportunities_path(@opportunity.employer) %>

app/views/admin/opportunities/export.csv.erb
<%= CSV.generate_line Opportunity.csv_headers -%>
<%- @opportunities.each do |opp| -%>
<%- next unless opp.csv_fields -%>
<%= CSV.generate_line(opp.csv_fields).html_safe -%>
<%- end -%>

app/views/admin/opportunities/index.csv.erb
<%= CSV.generate_line Opportunity.csv_headers %>
<%- @opportunities.each do |opp| -%>
<%- next unless opp.csv_fields %>
<%= CSV.generate_line(opp.csv_fields).html_safe -%>
<%- end -%>

app/views/admin/opportunities/index.html.erb
<h1><%= @employer ? "#{@employer.name} " : '' %>Opportunities</h1>

<p><%= link_to 'Add New Opportunity', (@employer ? new_admin_employer_opportunity_path(@employer) : admin_new_opportunity_path), class: 'button add' %></p>

<%= render "admin/opportunities/list", opportunities: @opportunities %>

<%= will_paginate @opportunities %>

app/views/admin/opportunities/new.html.erb
<h1><%= link_to @employer.name, admin_employer_path(@employer) %>: New Opportunity</h1>

<%= render 'form', employer: @employer, opportunity: @opportunity %>

<%= link_to 'Back', admin_employer_opportunities_path(@employer) %>

app/views/admin/opportunities/show.html.erb
<p>
  <strong>Opportunity Name:</strong>
  <%= @opportunity.name %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @opportunity.employer.name %>
</p>
<p>
  <strong>Job Posting URL:</strong>
  <%= link_to @opportunity.job_posting_url, @opportunity.job_posting_url, target: '_blank' %>
</p>
<p>
  <strong>Summary:</strong>
  <%= @opportunity.summary %>
</p>
<p>
  <strong>How to Apply:</strong>
  <%= @opportunity.how_to_apply %>
</p>


<%= render 'admin/industries/list', object: @opportunity %>
<%= render 'admin/interests/list', object: @opportunity %>

<h3>Active Candidates</h3>

<% if @opportunity.fellow_opportunities.empty? %>
  <p>There are no active candidates at this time.</p>
<% else %>
  <table class="fellows">
    <thead>
      <tr>
        <th>Name</th>
        <th>Stage</th>
        <th>Probability</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @opportunity.fellow_opportunities.sort_by{|fo| 0-fo.opportunity_stage.probability}.each do |candidacy| %>
        <%= form_for [:admin, candidacy], url: admin_candidate_path(candidacy), method: :put do |f| %>
          <tr>
            <td><%= link_to candidacy.fellow.full_name, admin_fellow_path(candidacy.fellow) %></td>
            <td><%= f.collection_select :opportunity_stage_id, OpportunityStage.order('position asc').all, :id, :name %></td>
            <td class="right"><%= sprintf("%d%%", candidacy.opportunity_stage.probability * 100) %></td>
            <td><%= f.submit 'Update' %></td>
            <td><%= link_to 'Archive', admin_candidate_path(candidacy), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Find Candidates', admin_opportunity_candidates_path(@opportunity), class: "button" %>

<footer class="actions">
  <%= link_to 'Edit', edit_admin_opportunity_path(@opportunity), class: 'edit' %> |
  <%= link_to 'Back', :back, class: 'back' %>
</footer>