config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  devise_for :users, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  
  match "/split" => Split::Dashboard, anchor: false, via: [:get, :post, :delete], constraints: ->(request) do
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    
    request.env['warden'].user.is_admin?
  end

  get 'home/welcome'
  get 'health_check', to: 'home#health_check'
  get 'login', to: 'home#login'
  get 'sso/:id', to: 'home#sso', as: 'sso'
  get 'token/:id', to: 'token#show', as: 'token'

  get 'candidates/:fellow_opportunity_id/status', to: 'candidates#status', as: 'candidate_status'
  
  resources :fellows, only: [:edit, :update]

  namespace :fellow do
    get 'home/welcome'
    post 'home/career'
    
    resource :profile, only: [:show, :edit, :update] do
      get :unsubscribe
    end
    
    resources :opportunities, only: [:show, :update]
  end

  namespace :admin do
    get 'home/welcome'
    get 'home/new_opportunity', as: 'new_opportunity'

    resources :employers, shallow: true do
      resources :locations
      resources :opportunities do
        resources :candidates, only: [:index, :create, :update, :destroy]
      end
    end
  
    resources :opportunities, only: [:index] do
      collection do
        post :export
      end
      
      member do
        put :unpublish
      end
    end

    resources :sites, shallow: true do
      resources :courses, except: [:index]
    end

    resources :fellows do
      collection do
        get :upload
        post :upload
      end
      
      member do
        get :resume
      end
    end

    resources :fellow_opportunities
    resources :opportunity_stages
    resources :employment_statuses
    resources :coaches

    resources :interests do
      collection do
        get :list
      end
    end

    resources :industries do
      collection do
        get :list
        get :combined
      end
    end

    resources :metros, only: [:index] do
      collection do
        get :list
        get :search
      end
    end
    
    resources :majors, only: [:index] do
      collection do
        get :list
      end
    end
    
    resources :cohort_fellows
    resources :cohorts
  end
  
  root to: "home#welcome"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/fellows_controller.rb
class Admin::FellowsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin!, except: [:resume]
  before_action :set_fellow, only: [:show, :edit, :update, :destroy, :resume]

  # GET /fellows
  # GET /fellows.json
  def index
    @fellows = Fellow.order(last_name: :asc, first_name: :asc).paginate(page: params[:page])
  end

  # GET /fellows/1
  # GET /fellows/1.json
  def show
  end
  
  # GET /fellows/1/resume.json
  def resume
    url = if @fellow.resume.attached?
      Rails.application.routes.url_helpers.url_for(@fellow.resume)
    else
      @fellow.resume_url
    end
    
    respond_to do |format|
      format.json { render json: {url: url}}
    end
  end

  # GET /fellows/new
  def new
    @fellow = Fellow.new
    @fellow.build_contact
  end

  # GET /fellows/1/edit
  def edit
    @fellow.build_contact if @fellow.contact.nil?
  end

  # POST /fellows
  # POST /fellows.json
  def create
    @fellow = Fellow.new(fellow_params)

    respond_to do |format|
      if @fellow.save
        format.html { redirect_to admin_fellows_path, notice: 'Fellow was successfully created.' }
        format.json { render :show, status: :created, location: @fellow }
      else
        format.html { render :new }
        format.json { render json: @fellow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fellows/1
  # PATCH/PUT /fellows/1.json
  def update
    respond_to do |format|
      if @fellow.update(fellow_params)
        format.html { redirect_to admin_fellows_path, notice: 'Fellow was successfully updated.' }
        format.json { render :show, status: :ok, location: @fellow }
      else
        format.html { render :edit }
        format.json { render json: @fellow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fellows/1
  # DELETE /fellows/1.json
  def destroy
    @fellow.destroy
    respond_to do |format|
      format.html { redirect_to admin_fellows_url, notice: 'Fellow was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  def upload
    if params[:csv]
      Fellow.delay.import(csv) 

      flash[:notice] = 'Your file is being uploaded, thanks! You can refresh this page to see updates.'
      redirect_to admin_fellows_path
    end
  end

  private
  
  def csv
    if params[:csv].respond_to?(:read)
      params[:csv].read
    else
      params[:csv]
    end
  end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_fellow
      @fellow = Fellow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fellow_params
      params.require(:fellow).permit(
        :key, :first_name, :last_name, :graduation_year, :graduation_semester, :graduation_fiscal_year, 
        :interests_description, :major, :affiliations, :gpa, :linkedin_url, :staff_notes, :efficacy_score, 
        :employment_status_id, :industry_tags, :interest_tags, :metro_tags, :major_tags, :industry_interest_tags,
        :resume, :receive_opportunities,
        opportunity_type_ids: [], industry_ids: [], interest_ids: [], metro_ids: [],
        contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
      )
    end
end

app/controllers/fellow/home_controller.rb
class Fellow::HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_fellow!
  before_action :set_fellow, only: [:welcome, :career]
  
  def welcome
  end
  
  def career
    @fellow.completed_career_steps = params[:career_steps]
    # redirect_to fellow_home_welcome_path
  end
  
  def new_opportunity
    @employers = Employer.all
  end
end

app/controllers/fellow/opportunities_controller.rb
class Fellow::OpportunitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_fellow!
  before_action :set_fellow
  before_action :set_candidate

  def show
    @content = YAML.load(File.read("#{Rails.root}/config/opportunity_stage_content.yml"))

    @fellow_opp = @candidate
    @fellow = @fellow_opp.fellow
    @opportunity = @fellow_opp.opportunity
    
    @token = AccessToken.for(@fellow_opp)
    @opportunity_stage = @fellow_opp.opportunity_stage
  end

  def update
    # if @fellow.update(fellow_params)
    #   redirect_to fellow_profile_path, notice: 'Your profile was successfully updated.'
    # else
    #   render :edit
    # end
  end
  
  private
  
  def set_fellow
    if @access_token
      @fellow = @access_token.owner.fellow
      return
    end
    
    unless current_user.fellow
      current_user.create_fellow(
        first_name: 'unknown',
        last_name: 'unknown',
        employment_status: EmploymentStatus.find_by(position: 0)
      )
    end
    
    @fellow = current_user.fellow
  end
  
  def set_candidate
    @candidate = @fellow.fellow_opportunities.find_by(id: params[:id])
  end
  
  def fellow_params
    # params.require(:fellow).permit(
    #   :key, :first_name, :last_name, :graduation_year, :graduation_semester,
    #   :major, :affiliations, :linkedin_url,
    #   :employment_status_id, :industry_tags, :interest_tags, :metro_tags, :industry_interest_tags,
    #   industry_ids: [], interest_ids: [], metro_ids: [],
    #   contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
    # )
  end
end

app/controllers/fellow/profiles_controller.rb
class Fellow::ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:list, :combined]
  before_action :ensure_fellow!
  before_action :set_fellow

  def show
  end

  def edit
  end

  def update
    if @fellow.update(fellow_params)
      redirect_to fellow_profile_path, notice: 'Your profile was successfully updated.'
    else
      render :edit
    end
  end
  
  def unsubscribe
    @fellow.ignore_opportunities!
  end
  
  private
  
  def fellow_params
    params.require(:fellow).permit(
      :key, :first_name, :last_name, :graduation_year, :graduation_semester,
      :major, :affiliations, :linkedin_url, :receive_opportunities, :resume,
      :employment_status_id, :industry_tags, :interest_tags, :major_tags, :metro_tags, :industry_interest_tags,
      opportunity_type_ids: [], industry_ids: [], interest_ids: [], metro_ids: [],
      contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
    )
  end
end

app/controllers/fellows_controller.rb
class FellowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_fellow

  def edit
    @fellow.build_contact if @fellow.contact.nil?
  end

  def update
    unless @fellow.update(fellow_params)
      render :edit
    end
  end

  private
  
  def set_fellow
    @fellow = Fellow.find(params[:id])
  end

  def fellow_params
    params.require(:fellow).permit(
      :key, :first_name, :last_name, :graduation_year, :graduation_semester, :graduation_fiscal_year, 
      :interests_description, :major, :affiliations, :gpa, :linkedin_url, :staff_notes, :efficacy_score, 
      :employment_status_id, :industry_tags, :interest_tags, :metro_tags, :industry_interest_tags,
      industry_ids: [], 
      interest_ids: [],
      metro_ids: [],
      contact_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :phone, :email, :url]
    )
  end
end

app/helpers/fellow/profile_helper.rb
module Fellow::ProfileHelper
end

app/helpers/fellows_helper.rb
module FellowsHelper
end

app/views/admin/fellows/_form.html.erb
<%= form_with(model: [:admin, fellow], local: true, multipart: true) do |form| %>
  <% if fellow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fellow.errors.count, "error") %> prohibited this fellow from being saved:</h2>

      <ul>
      <% fellow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :resume, 'Resume PDF' %>
    <%= form.file_field :resume %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, required: true %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, required: true %>
  </div>

  <div class="field">
    <%= form.label :graduation_year %>
    <%= form.number_field :graduation_year %>
  </div>

  <div class="field">
    <%= form.label :graduation_semester, 'Graduation term' %>
    <%= form.select :graduation_semester, options_for_select(Course::VALID_SEMESTERS) %>
  </div>

  <div class="field">
    <%= form.label :graduation_fiscal_year %>
    <%= form.number_field :graduation_fiscal_year %>
  </div>

  <div class="field">
    <%= form.label :affiliations %>
    <%= form.text_area :affiliations %>
  </div>

  <div class="field">
    <%= form.label :gpa %>
    <%= form.text_field :gpa %>
  </div>

  <div class="field">
    <%= form.label :linkedin_url %>
    <%= form.text_field :linkedin_url %>
  </div>

  <div class="field">
    <%= form.label :staff_notes %>
    <%= form.text_area :staff_notes %>
  </div>

  <div class="field">
    <%= form.label :efficacy_score %>
    <%= form.text_field :efficacy_score %>
  </div>

  <div class="field">
    <%= form.label :employment_status_id %>
    <%= form.collection_select(:employment_status_id, EmploymentStatus.all, :id, :name) %>
  </div>
  
  <div class="field">
    <%= form.check_box :receive_opportunities %>
    <%= form.label :receive_opportunities, 'Receive Career Opportunties from Braven?', class: 'checkbox' %>
  </div>
  
  <hr>

  <%= render 'admin/contacts/nested_form', form: form %>

  <%= render 'admin/opportunity_types/check_boxes', fellow: fellow %>
  
  <div id="interests-collection">
    <h3>Industries/Interests</h3>

    <div id="industry-interest-tags" class="jquery-tags">
      <%= form.text_area :industry_interest_tags %>
    </div>

    <%= link_to 'full list', combined_admin_industries_path, target: '_blank', class: 'full-list' %>
  </div>
  
  <div id="majors-collection">
    <h3>Majors/Minors</h3>

    <div id="major-tags" class="jquery-tags">
      <%= form.text_area :major_tags %>
    </div>

    <%= link_to 'full list', list_admin_majors_path, target: '_blank', class: 'full-list' %>
  </div>
  
  <div id="metros-collection">
    <h3>Where Fellow Would Like to Work</h3>
  
    <div id="metro-tags" class="jquery-tags">
      <%= form.text_area :metro_tags, class: 'metro-tags' %>
    </div>

    <%= link_to 'full list', list_admin_metros_path, target: '_blank', class: 'full-list' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/fellows/edit.html.erb
<h1>Editing Fellow</h1>

<%= render 'form', fellow: @fellow %>

<%= link_to 'Show', admin_fellow_path(@fellow) %> |
<%= link_to 'Back', admin_fellows_path %>

app/views/admin/fellows/index.html.erb
<h1>Fellows</h1>

<table class="fellows wide">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Graduation</th>
      <th>Major</th>
      <th>GPA</th>
      <th>Efficacy score</th>
      <th>Employment status</th>
      <th>Resumé</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @fellows.each do |fellow| %>
      <tr>
        <td><%= fellow.key %></td>
        <td><%= link_to fellow.full_name, admin_fellow_path(fellow) %></td>
        <td><%= fellow.graduation %></td>
        <td><%= fellow.major || 'N/A' %></td>
        <td><%= fellow.gpa || 'N/A' %></td>
        <td><%= fellow.efficacy_score || 'N/A' %></td>
        <td><%= fellow.employment_status.name %></td>
        <td><%= resume_link(fellow) %></td>
        <td><%= link_to 'Edit', edit_admin_fellow_path(fellow), class: 'edit' %></td>
        <td><%= link_to 'Delete', admin_fellow_path(fellow), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @fellows %>

<br>

<%= link_to 'New Fellow', new_admin_fellow_path %> |
<%= link_to 'Upload Fellows via CSV', upload_admin_fellows_path %>

app/views/admin/fellows/new.html.erb
<h1>New Fellow</h1>

<%= render 'form', fellow: @fellow %>

<%= link_to 'Back', admin_fellows_path %>

app/views/admin/fellows/show.html.erb
<h1><%= @fellow.first_name %> <%= @fellow.last_name %></h1>

<table>
  <tbody>
    <tr class="key">
      <th>Key:</th>
      <td><%= @fellow.key %></td>
    </tr>
    <tr>
      <th>Resumé:</th>
      <td><%= resume_link(@fellow) %></td>
    </tr>
    <tr class="new-section">
      <th>Graduation year:</th>
      <td><%= @fellow.graduation_year %></td>
    </tr>
    <tr>
      <th>Graduation semester:</th>
      <td><%= @fellow.graduation_semester %></td>
    </tr>
    <tr>
      <th>Graduation fiscal year:</th>
      <td><%= @fellow.graduation_fiscal_year %></td>
    </tr>
    <tr>
      <th>Industries/Interests:</th>
      <td><%= @fellow.industry_interest_tags.gsub(';', ', ') %></td>
    </tr>
    <tr>
      <th>Majors:</th>
      <td><%= @fellow.major_tags.gsub(';', ', ') %></td>
    </tr>
    <tr>
      <th>Preferred Locations:</th>
      <td><%= @fellow.metro_tags.gsub(';', ', ') %></td>
    </tr>
    <tr>
      <th>Affiliations:</th>
      <td><%= @fellow.affiliations %></td>
    </tr>
    <tr>
      <th>Gpa:</th>
      <td><%= @fellow.gpa %></td>
    </tr>
    <tr>
      <th>Linkedin url:</th>
      <td><%= @fellow.linkedin_url %></td>
    </tr>
    <tr>
      <th>Staff notes:</th>
      <td><%= @fellow.staff_notes %></td>
    </tr>
    <tr>
      <th>Efficacy score:</th>
      <td><%= @fellow.efficacy_score %></td>
    </tr>
    <tr>
      <th>Employment status:</th>
      <td><%= @fellow.employment_status.name %></td>
    </tr>
    <tr>
      <th>Contact about Opportunities:</th>
      <td><%= @fellow.receive_opportunities ? 'yes' : 'no' %></td>
    </tr>
  </tbody>
</table>

<h3>Contact Info</h3>

<table>
  <tbody>
    <tr class="key">
      <th>Phone:</th>
      <td><%= @fellow.contact.phone %></td>
    </tr>
    <tr>
      <th>E-Mail:</th>
      <td>
        <% if @fellow.contact.email.present? %>
          <%= link_to @fellow.contact.email, "mailto:#{@fellow.contact.email}" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Address:</th>
      <td><%= address_for(@fellow.contact) %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_admin_fellow_path(@fellow) %> |
<%= link_to 'Back', admin_fellows_path %>

app/views/admin/fellows/upload.html.erb
<h1>Import Fellows</h1>

<p>Upload a CSV export of the PAF Master Roster to import/update fellow records.</p>

<p>
  <b>Instructions:</b> Go to the 
  <%= link_to 'PAF Master Roster', 'https://docs.google.com/spreadsheets/d/1v7hP0ggHRjpr-kZumEwkhGWxhBWNoWQCZJGMIp6SyOM', target: '_blank' %>
  and click on the "Summer Ops Tracker" tab. In the top menu, select "File -> Download as... -> Comma-separated values". Save the file, and upload it here.

<%= form_tag upload_admin_fellows_path, multipart: true do %>
  <div class="field">
    <%= file_field_tag :csv %>
  </div>

  <div class="field">
    <%= submit_tag 'Upload Roster' %>
  </div>
<% end %>

<%= link_to 'Back', admin_fellows_path %>