config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  devise_for :users, controllers: { confirmations: 'confirmations', sessions: 'sessions', passwords: 'passwords' }
  
  match "/split" => Split::Dashboard, anchor: false, via: [:get, :post, :delete], constraints: ->(request) do
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    
    request.env['warden'].user.is_admin?
  end

  get 'home/welcome'
  get 'health_check', to: 'home#health_check'
  get 'login', to: 'home#login'
  get 'sso/:id', to: 'home#sso', as: 'sso'
  get 'token/:id', to: 'token#show', as: 'token'

  get 'candidates/:fellow_opportunity_id/status', to: 'candidates#status', as: 'candidate_status'
  
  resources :fellows, only: [:edit, :update]

  namespace :fellow do
    get 'home/welcome'
    post 'home/career'
    
    resource :profile, only: [:show, :edit, :update] do
      get :unsubscribe
    end
    
    resources :opportunities, only: [:show, :update]
  end

  namespace :admin do
    get 'home/welcome'
    get 'home/new_opportunity', as: 'new_opportunity'

    resources :employers, shallow: true do
      resources :locations
      resources :opportunities do
        resources :candidates, only: [:index, :create, :update, :destroy]
      end
    end
  
    resources :opportunities, only: [:index] do
      collection do
        post :export
      end
      
      member do
        put :unpublish
      end
    end

    resources :sites, shallow: true do
      resources :courses, except: [:index]
    end

    resources :fellows do
      collection do
        get :upload
        post :upload
      end
      
      member do
        get :resume
      end
    end

    resources :fellow_opportunities
    resources :opportunity_stages
    resources :employment_statuses
    resources :coaches

    resources :interests do
      collection do
        get :list
      end
    end

    resources :industries do
      collection do
        get :list
        get :combined
      end
    end

    resources :metros, only: [:index] do
      collection do
        get :list
        get :search
      end
    end
    
    resources :majors, only: [:index] do
      collection do
        get :list
      end
    end
    
    resources :cohort_fellows
    resources :cohorts
  end
  
  root to: "home#welcome"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/industry.rb
class Industry < ApplicationRecord
  has_and_belongs_to_many :employers
  has_and_belongs_to_many :opportunities
  has_and_belongs_to_many :fellows
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/industries_controller.rb
class Admin::IndustriesController < ApplicationController
  before_action :authenticate_user!, except: [:list, :combined]
  before_action :ensure_admin!, except: [:list, :combined]
  before_action :set_industry, only: [:show, :edit, :update, :destroy]

  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.order('name asc').all
  end
  
  def list
    @industries = Industry.order('name asc').all
    render layout: false
  end
  
  def combined
    @names = (Industry.pluck(:name) | Interest.pluck(:name)).sort
    
    respond_to do |format|
      format.html { render layout: false }
      format.json { render json: @names}
    end
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to admin_industries_path, notice: 'Industry was successfully created.' }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industries/1
  # PATCH/PUT /industries/1.json
  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to admin_industries_path, notice: 'Industry was successfully updated.' }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    industry_name = @industry.name
    
    @industry.destroy
    respond_to do |format|
      format.html { redirect_to admin_industries_url, notice: "Industry #{industry_name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def industry_params
      params.require(:industry).permit(:name, :description)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/admin/industries/_check_boxes.html.erb
<% object_name = object.class.name.downcase %>  
<div id="industry-checklist" class="industries checklist">
  <% Industry.order('name asc').each do |industry| %>
    <% tag_id = "industry_ids_#{industry.id}" %>
    
    <%= check_box_tag("#{object_name}[industry_ids][]", industry.id, object.industries.include?(industry), id: tag_id, class: "industry_checkbox") %>
    <%= label_tag(tag_id, industry.name, style: 'display: inline;') %><br>
  <% end %>

  <%= link_to 'see shorter list', '#', id: 'industry-short-list' %>
</div>

app/views/admin/industries/_form.html.erb
<%= form_with(model: [:admin, industry], local: true) do |form| %>
  <% if industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% industry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/industries/_list.html.erb
<p class="tags-header"><strong>Related Industries</strong></p>
<ul>
  <% object.industries.each do |industry| %>
    <li><%= industry.name %></li>
  <% end %>
</ul>

app/views/admin/industries/combined.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Career Manager</title>
  </head>

  <body>
    <main>
      <h1>Industries/Interests/Majors</h1>
      <p><strong>Tip:</strong> Click ctrl+F (cmd+F on a Mac) to find an item.</p>
      <ul>
        <% @names.each do |name| %>
          <li><%= name %></li>
        <% end %>
      </ul>
    </main>
  </body>
</html>

app/views/admin/industries/edit.html.erb
<h1>Editing Industry</h1>

<%= render 'form', industry: @industry %>

<%= link_to 'Show', admin_industry_path(@industry) %> |
<%= link_to 'Back', admin_industries_path %>

app/views/admin/industries/index.html.erb
<h1>Industries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Opportunities</th>
      <th>Fellows</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= link_to industry.name, admin_industry_path(industry) %></td>
        <td class="numeric"><%= industry.opportunities.count %></td>
        <td class="numeric"><%= industry.fellows.count %></td>
        <td><%= link_to 'Edit', edit_admin_industry_path(industry), class: 'edit' %></td>
        <td>
          <% if industry.opportunities.count + industry.fellows.count == 0 %>
            <%= link_to 'Delete', admin_industry_path(industry), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Industry', new_admin_industry_path, class: 'button add' %>

app/views/admin/industries/list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Career Manager</title>
  </head>

  <body>
    <main>
      <h1>Industries</h1>
      
      <ul>
        <% @industries.each do |industry| %>
          <li><%= industry.name %></li>
        <% end %>
      </ul>
    </main>
  </body>
</html>

app/views/admin/industries/new.html.erb
<h1>New Industry</h1>

<%= render 'form', industry: @industry %>

<%= link_to 'Back', admin_industries_path %>

app/views/admin/industries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @industry.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @industry.description %>
</p>

<footer class="actions">
  <%= link_to 'Edit', edit_admin_industry_path(@industry), class: 'edit' %> |
  <%= link_to 'Back', admin_industries_path, class: 'back' %>
</footer>